### ISSUE TITLE
Can't define CSS animations with the current options

### ISSUE THREAD

**Issue by 64J0** [Zaid-Ajaj/Feliz#391]
Hello guys, hope you're good. With the current CSS inside components options, I think it's impossible to write CSS animations.

For instance, I'm trying to do this: https://stackoverflow.com/questions/6410730/css-endless-rotation-animation.

**Comment by Zaid-Ajaj** [comment]
Hi @64J0, for anything that requires advanced CSS, using inline styles might not be the best option. 

It is a lot easier to simply use CSS instead and import it into the component. 

For example, write your CSS in a module
```css
/* animations.module.css */
@-webkit-keyframes rotating /* Safari and Chrome */ {
  from {
    -webkit-transform: rotate(0deg);
    -o-transform: rotate(0deg);
    transform: rotate(0deg);
  }
  to {
    -webkit-transform: rotate(360deg);
    -o-transform: rotate(360deg);
    transform: rotate(360deg);
  }
}
@keyframes rotating {
  from {
    -ms-transform: rotate(0deg);
    -moz-transform: rotate(0deg);
    -webkit-transform: rotate(0deg);
    -o-transform: rotate(0deg);
    transform: rotate(0deg);
  }
  to {
    -ms-transform: rotate(360deg);
    -moz-transform: rotate(360deg);
    -webkit-transform: rotate(360deg);
    -o-transform: rotate(360deg);
    transform: rotate(360deg);
  }
}
.rotating {
  -webkit-animation: rotating 2s linear infinite;
  -moz-animation: rotating 2s linear infinite;
  -ms-animation: rotating 2s linear infinite;
  -o-animation: rotating 2s linear infinite;
  animation: rotating 2s linear infinite;
}
```
Then import the CSS class into your component (assuming you are using the Feliz template or the SAFE template)
```fs
// Stylesheet API
// let stylehsheet = Stylesheet.load "./fancy.module.css"
// stylesheet.["fancy-class"] which returns a string
module Stylesheet =

    type IStylesheet =
        [<Emit "$0[$1]">]
        abstract Item : className:string -> string

    /// Loads a CSS module and makes the classes within available
    let inline load (path: string) = importDefault<IStylesheet> path

let animations = Stylesheet.load "./animations.module.css"

[<ReactComponent>]
let Index() = 
  Html.div [
    prop.className animations.["rotating"]
    prop.text "I am rotating"
  ]
```
Hope this helps 😄
